### ISSUE TITLE
Bug with the banning system

### ISSUE THREAD

**Issue by Tomi321** [NevoSwissa/CL-PoliceGarageV2#3]
Hey, I'm kinda new to server developing, and I was trying out your script, when the script randomly banned me. I can't find where it stored my ban, it's not showing up on the txadmin page. About the ban: I had the police job that was needed for it, I had the cash money that was required for the car to be bought, and I had the highest rank in the department. I have no idea why it banned me, and I can't seem to find where it stored my ban. Please help

**Comment by NevoSwissa** [comment]
Firstly I would like to apologize for the inconvenience the script caused you, you can remove bans from the database in the table "bans". And try to update to the current version of the script where this issue should be fixed !

**Comment by NevoSwissa** [comment]
If you need any more help feel free to open a ticket in our Discord server

**Comment by Tomi321** [comment]
Thanks for the help, it seems to be working now.
